### ISSUE TITLE
Domain Suffix not being recognized.

### ISSUE THREAD

**Issue by deonte1threatt** [BlueBubblesApp/bluebubbles-app#1851]
It seems the "manual setup" in the app and web app are filtering website types. 
My domian has a suffix of .network and it throws an error. 
using a .com gets a connecting page, however I want to keep things central.

![image](https://user-images.githubusercontent.com/31520371/150426652-b6b1633b-c43a-46e1-a6c5-bcf3dddb2562.png)

**Comment by tneotia** [comment]
To whoever addresses this:

1. Check the Getx regex for isUrl and see what it is doing, does it whitelist a bunch of "known" domains? If so, just make a custom one with .network also whitelisted
2. If the above is not true, find some regex that is a bit more forgiving for URLs

**Comment by tneotia** [comment]
Fixed via https://github.com/BlueBubblesApp/bluebubbles-app/commit/68752acedfc56815d4c19516d5d48501a848d3fb

**Comment by deonte1threatt** [comment]
I'm still seeing the same error even after clearing cache and cookies.  @tneotia 

Is there anything more I need to do on my end?

**Comment by tneotia** [comment]
We haven't published updated versions with the fix quite yet. The latest desktop app in github *might* have the fix, but don't quote me on that.
